### ISSUE TITLE
Precaching bug with `adapter-static` and `load()` functions

### ISSUE THREAD

**Issue by WhyAsh5114** [vite-pwa/sveltekit#98] opened 2024-12-31 10:03 UTC
## The main problem

There's a specific bug when using `load()` functions along with prerendering and the static-adapter that I spent 
hours trying to fix, it occurs primarily due to `@vite-pwa/sveltekit` not being able to figure out how to cache 
the returned data from the `load()`, typically stored in:
```
.svelte-kit/output/prerendered/dependencies/{page-route}/__data.json
```
This causes the app to break when offline and navigating to a page that depends on that data.

## The hacky fix

1. To fix this, you need to manipulate the PWA config in `vite.config.ts` and the custom `service-worker` file.
After setting up the basic PWA, I added the following to your `vite.config.ts`:
```js
export default defineConfig({
  plugins: [
    sveltekit(),
    SvelteKitPWA({
      /* other config */
      injectManifest: {
        globPatterns: [
          'client/**/*.{js,css,ico,png,svg,webp,webmanifest,ttf,woff,woff2}',
          'prerendered/**/*.{html,json}'
        ],
      }
    })
  ],
});
```

2. Notice the `prerendered/**/*.{html,json}` in the `globPatterns` array, this tells `vite-plugin-pwa` to cache the
prerendered data (typically in the form of `__data.json` files) so that the app can work offline. This should have
been enough, but for some reason you need this weird hack in your `service-worker.ts`:

```typescript
/// <reference lib="WebWorker" />
/// <reference types="@sveltejs/kit" />

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';
declare let self: ServiceWorkerGlobalScope;

const manifest = self.__WB_MANIFEST;

manifest.forEach((entry) => {
	if (typeof entry === 'object' && entry.url.endsWith('__data.json')) {
		entry.url = entry.url.replace(/^prerendered\/dependencies\//, '');
	}
});

cleanupOutdatedCaches();
precacheAndRoute(manifest, { ignoreURLParametersMatching: [/.*/] });

self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

registerRoute(/.*/, new StaleWhileRevalidate());
```

This hack is necessary because the `__data.json` files are stored in the `prerendered/dependencies/` folder, and the
service worker's default behaviour incorrectly configures their URLs. This hack manually alters the URLs so that the
service worker can cache them correctly.

**Comment by userquin** [comment] 2024-12-31 11:10
can you provide a minimal reproduction and so I can check the kit folder? Right now I'm fixing similar problem for Kit SPA mode...

Or just updload an screenshot like this one (this is for SPA using static adatper):
![imagen](https://github.com/user-attachments/assets/5bfee30d-177c-4a63-8a3e-2acc4511082d)

**Comment by userquin** [comment] 2024-12-31 11:37
I'm going to update the `buildGlobPatterns` function to include `json` and `js` files and removing also `'prerendered/dependencies/'` prefix in the manifest transform:

```js
function buildGlobPatterns(globPatterns?: string[]) {
  if (globPatterns) {
    if (!globPatterns.some(g => g.startsWith('prerendered/')))
      globPatterns.push('prerendered/**/*.{html,json,js}')

    if (!globPatterns.some(g => g.startsWith('client/')))
      globPatterns.push('client/**/*.{js,css,ico,png,svg,webp,webmanifest}')

    if (!globPatterns.some(g => g.includes('webmanifest')))
      globPatterns.push('client/*.webmanifest')

    return globPatterns
  }

  return ['client/**/*.{js,css,ico,png,svg,webp,webmanifest}', 'prerendered/**/*.{html,json,js}']
}
```

**Comment by WhyAsh5114** [comment] 2024-12-31 11:46
Yep, that should fix it

**Comment by WhyAsh5114** [comment] 2024-12-31 11:54
Also, I had another doubt. When using this strategy, the `$offlineReady` store returned from the `useRegisterSW()` function is never true. 

Am I misunderstanding something? How would I know if all the assets have been precached on the frontend?

**Comment by userquin** [comment] 2024-12-31 12:04
`$offlineReady` will be called/activated only once, when the service worker is installed and activated first time.

Uhmmm, looks like the `.svelte-kit/output/prerendered/dependencies/_app/env.js` file is added after PWA plugin builds the service worker, and so there is no way to fix this: I'm going to update https://github.com/vite-pwa/sveltekit/pull/97 with previous fix, can you test it in your local with this dependency https://pkg.pr.new/@vite-pwa/sveltekit@488aa8c ?

**Comment by WhyAsh5114** [comment] 2024-12-31 12:05
sure, I'll let you know

**Comment by userquin** [comment] 2024-12-31 12:06
@WhyAsh5114 are you using SPA https://svelte.dev/docs/kit/single-page-apps?

**Comment by WhyAsh5114** [comment] 2024-12-31 12:06
not really, I'm using adapter-static, with export const prerender = true in root layout.ts

**Comment by userquin** [comment] 2024-12-31 12:09
> Am I misunderstanding something? How would I know if all the assets have been precached on the frontend?

You need to check it in the browser devtools: Application > Cache Storage

![image](https://github.com/user-attachments/assets/9b23a898-6fa5-4b00-82ec-44eeb9952122)

> not really, I'm using adapter-static, with export const prerender = true in root layout.ts

Can you provide a minimal reproduction?

**Comment by WhyAsh5114** [comment] 2024-12-31 12:09
> Uhmmm, looks like the .svelte-kit/output/prerendered/dependencies/_app/env.js file
Also, the env.js file isn't really of interest, the `__data.json` files are though IMO, since when I navigate using button clicks on the app, the SW tries to fetch that page's `__data.json` if it has a `load()` (or maybe `$props()/export let data`).

Ohkk, I'll make a minimal repro and link it here.

**Comment by userquin** [comment] 2024-12-31 12:13
Since you're using static adapter (SPA requires it), maybe moving the `buildEnd`  hook from `pre` to `post` works, I need to do some tests.

I have no idea why kit not applying adapter logic like normal build, looks like `prerendered/dependencies` files built without awaiting... (maybe a bug => missing await somewhere).

**Comment by WhyAsh5114** [comment] 2024-12-31 12:19
Minimal repro: https://github.com/WhyAsh5114/prerendered-pwa

**Comment by userquin** [comment] 2024-12-31 12:31
Thx, looks like we need to move the kit pwa build plugin from 'pre' to 'post' (register it after kit), this way we've now `prerendered/dependencies/_app/env.js` in the sw precache manifest.

**Comment by userquin** [comment] 2024-12-31 12:39
There is a problem, now the service worker being generated in the kit output folder, but the adapter will not copy the service worker since it is being generated after the adapter runs (the adapter will copy the client folder without the sw).

**Comment by WhyAsh5114** [comment] 2024-12-31 12:42
hmm, but again, why would we need the `env.js` file? does it work if we just get `__data.json`? 

Or are those files also generated after the PWA plugin builds?

**Comment by WhyAsh5114** [comment] 2024-12-31 12:43
I'm not even sure it contains anything useful, in my minimal repro it's just this:
```
export const env={}
```

**Comment by userquin** [comment] 2024-12-31 12:50
I'm going to check your reproduction, looks like the `$service-worker` not including the `_app/env.js` file in the `build/files`.

**Comment by WhyAsh5114** [comment] 2024-12-31 12:52
Yes, my globPattern doesn't include JS from the `prerendered/client` dir, only `html,json`
```
                                globPatterns: [
					'client/**/*.{js,css,ico,png,svg,webp,webmanifest,ttf,woff,woff2}',
					'prerendered/**/*.{html,json}'
				]
```

**Comment by userquin** [comment] 2024-12-31 13:00
ok, the fix will work for `__data.json` files, kit is generating them since we've the entries in the sw precache manifest.

**Comment by userquin** [comment] 2024-12-31 13:04
And working offline:

![image](https://github.com/user-attachments/assets/be476e9d-746f-4175-8acf-24d0ea311793)

**Comment by WhyAsh5114** [comment] 2024-12-31 13:08
Yep, perfect. I expected this by default, maybe we should also update the docs for this, let me know if I can help!

**Comment by userquin** [comment] 2024-12-31 13:08
I'm going to release a patch version, in the meantime you can check it in your local with this dependency: https://pkg.pr.new/@vite-pwa/sveltekit@a7c0605 (I guess once PR merged the pkg.pr.new is removed)

**Comment by userquin** [comment] 2024-12-31 13:09
> Yep, perfect. I expected this by default, maybe we should also update the docs for this, let me know if I can help!

Checking the docs...

**Comment by userquin** [comment] 2024-12-31 13:31
https://github.com/vite-pwa/docs/pull/172

**Comment by WhyAsh5114** [comment] 2024-12-31 13:55
> I'm going to release a patch version, in the meantime you can check it in your local with this dependency: https://pkg.pr.new/@vite-pwa/sveltekit@a7c0605 (I guess once PR merged the pkg.pr.new is removed)

Umm, I installed this and remove my custom URL manipulation. It doesn't seem to work, did you push the patch?
![image](https://github.com/user-attachments/assets/56db19be-53d8-45e7-ad03-f57e95b52a9b)

And the docs change looks good.

**Comment by userquin** [comment] 2024-12-31 14:02
Remove the storage including the service worker and reload the page, you may have old sw (you should use a virtual, vanillajs or sveltekit for page reload)

**Comment by WhyAsh5114** [comment] 2024-12-31 14:04
Yes, I did try that, clear storage, empty cache and hard reload. I was still getting this error

**Comment by userquin** [comment] 2024-12-31 14:08
Try adding `includeVersionFile: true`  to kit pwa options

**Comment by WhyAsh5114** [comment] 2024-12-31 14:10
Still the same, it only happens when I go offline. The cache entry is there though
![image](https://github.com/user-attachments/assets/2a6546cc-f43f-4256-8ef1-f39a914f5baa)

**Comment by userquin** [comment] 2024-12-31 14:12
Check if you have checked `Disable cache` in network tab, uncheck it:

![imagen](https://github.com/user-attachments/assets/9b2dc724-7882-4952-8fc6-2eb2b0363b41)

**Comment by WhyAsh5114** [comment] 2024-12-31 14:13
> And working offline:
> 
> ![image](https://private-user-images.githubusercontent.com/6311119/399475738-be476e9d-746f-4175-8acf-24d0ea311793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTI0ODAsIm5iZiI6MTczNTY1MjE4MCwicGF0aCI6Ii82MzExMTE5LzM5OTQ3NTczOC1iZTQ3NmU5ZC03NDZmLTQxNzUtOGFjZi0yNGQwZWEzMTE3OTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMTMzNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGZkZWZjZTg2YjlkOTI4NGMwZTVhOWZmODg4MDRkNDMzZTc3NWY0ZGE0OTAxNDViODUxNDg0YjI2YjFiMmEyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.F2Dc3hcdIHgH-NsbL12RqQl0EnBqvegRUJ_B1jX9Lmo)

Try doing it in this way:
1. npm run bulid && npm run preview
2. go to localhost:4173
3. now go offline and try to click on the link

**Comment by WhyAsh5114** [comment] 2024-12-31 14:13
> Check if you have checked `Disable cache` in network tab, uncheck it:
> 
> ![imagen](https://private-user-images.githubusercontent.com/6311119/399483965-9b2dc724-7882-4952-8fc6-2eb2b0363b41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NTQ2NTMsIm5iZiI6MTczNTY1NDM1MywicGF0aCI6Ii82MzExMTE5LzM5OTQ4Mzk2NS05YjJkYzcyNC03ODgyLTQ5NTItOGZjNi0yZWIyYjAzNjNiNDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMzFUMTQxMjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZmZWY0ODY1ZGJhMjJiYjA4ZGNkNjEwMmZlYzc4ZDUzMjFhNjVhMGY5YzZiZGJlZTQ0NGQxODQyNDQ1OTZlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2_QbP589ei6_xmlGc-o1H0TYW74XSk8PMYXr3ZBNQJg)

it is unchecked

**Comment by userquin** [comment] 2024-12-31 14:14
![imagen](https://github.com/user-attachments/assets/e3cc0e28-7a77-4cae-ae26-6078b380f2fd)

**Comment by WhyAsh5114** [comment] 2024-12-31 14:15
You are getting that after removing the url manipulation from the service worker?
If so, I'm messing something up on my side, this package was the one I was supposed to install right?
```
		"@vite-pwa/sveltekit": "https://pkg.pr.new/@vite-pwa/sveltekit@a7c0605",
```

**Comment by userquin** [comment] 2024-12-31 14:17
wait, I'm using local tgz file, checking changes...

**Comment by userquin** [comment] 2024-12-31 14:17
In the meantime add the pwa icons...

**Comment by userquin** [comment] 2024-12-31 14:23
Use this link https://pkg.pr.new/@vite-pwa/sveltekit@97

**Comment by WhyAsh5114** [comment] 2024-12-31 14:23
Ohk, need to head out for a bit, will get back in an hour or two and add the icons

**Comment by userquin** [comment] 2024-12-31 14:24
![imagen](https://github.com/user-attachments/assets/71475dc1-b469-43d3-903e-cf811eafe971)

![imagen](https://github.com/user-attachments/assets/6187a245-3317-4879-8270-62f329dcde8b)

**Comment by userquin** [comment] 2024-12-31 14:26
Oh, we need font  files (ttf,woff*), don't remove first globPattern.

**Comment by userquin** [comment] 2024-12-31 15:54
@WhyAsh5114 kit pwa v0.6.7 released

**Comment by WhyAsh5114** [comment] 2024-12-31 16:07
Hey, it works!

I forgot to use `registerRoute()` on the paths so the sw wasn't participating in the fetch at all. My bad.

Once I added that, with v0.6.7, it works properly. Thank you very much!

**Comment by WhyAsh5114** [comment] 2024-12-31 17:06
Okay, maybe its not fully done yet. There's still some weird behavior. I've update the repro to include it. Steps to create an error:

1. `npm run build && npm run preview`
2. In a new private tab, cleared everything, empty cache and hard reload
3. Go offline
4. Stay on the root page, don't go to `/dependent` at all **(important)**
5. Hover on the link to go to `/dependent`, there'll be errors in the console
![image](https://github.com/user-attachments/assets/4a3bc9dc-cdc3-4e20-adab-ac836e5dfe0a)
6. Even though the `__data.json` is cached, you'll still get this. But for some reason, manually changing the URL to `localhost:4173/dependent` will work without errors, and you can then go back and forth.
7. But starting from root (`localhost:4173`), and immediately going offline, and then trying to go to `/dependent` with the URL breaks it

**Comment by WhyAsh5114** [comment] 2024-12-31 17:09
For some reason, hovering (and clicking) on the link element, the request doesn't go through the service-worker.

**Comment by userquin** [comment] 2024-12-31 17:52
Check https://github.com/WhyAsh5114/prerendered-pwa/pull/1 (about prefetching when hovering the links no idea what's happening).

The PR including pwa icons (from kit pwa example) and removed manifest.webamanifest t¡from static folder addding the content to pwa manifest option).

**Closed** 2024-12-31 18:02 UTC
Labels: bug

**Comment by WhyAsh5114** [comment] 2024-12-31 18:33
@userquin, I did merge it and tried to run it again. It still errors out when doing the steps mentioned above. But yeah, this issue has been fixed, its something I need to figure out on my own with workbox docs and all.

**Comment by userquin** [comment] 2024-12-31 18:57
@WhyAsh5114 can you replace `/./` with `/.*/` in the sw?

**Comment by WhyAsh5114** [comment] 2024-12-31 19:01
yep, tried that, still issues

I'll look into the mentioned issue tomorrow, a bit tired rn

**Comment by WhyAsh5114** [comment] 2025-01-01 07:47
@userquin Okay, I finally fixed it. All we just needed to do was:
```ts
self.addEventListener('activate', (event) => {
	event.waitUntil(self.clients.claim());
	console.log('Service worker activated');
});
```

The service worker wasn't taking control on the initial page load, and therefore unable to serve cache resulting in errors as the requests were not being passed to it anyways. 

There was no need to modify the registration logic in the root `+layout.svelte` or even include the version file in the kit config. Updated the repro to reflect all this with default config and still working.

**Comment by WhyAsh5114** [comment] 2025-01-01 07:50
> In brief:
The install event is the first event a service worker gets, and it only happens once.
A promise passed to installEvent.waitUntil() signals the duration and success or failure of your install.
A service worker won't receive events like fetch and push until it successfully finishes installing and becomes "active".
**By default, a page's fetches won't go through a service worker unless the page request itself went through a service worker. So you'll need to refresh the page to see the effects of the service worker.
clients.claim() can override this default, and take control of non-controlled pages.**

https://web.dev/articles/service-worker-lifecycle

**Comment by userquin** [comment] 2025-01-01 09:57
You're using  auto update, the code should be:
```ts

self.skipWaiting()
self.addEventListener('activate', (event) => {
	event.waitUntil(self.clients.claim());
	console.log('Service worker activated');
});

/* THIS IS USED FOR PROMPT FOR UPDATE: CLIENTS WILL NOT EMIT THIS EVENT
self.addEventListener('message', (event) => {
	if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});
*/
```

**Comment by userquin** [comment] 2025-01-01 10:02
About the logic in the layout, you should avoid calling `r.update()` when offline, that callback is deprecated, use the new one with the sw url: when your code base grows, if you call update while updating you may have some problems, increase the timeout in production, 30 minutes or even more should be fine.

**Comment by WhyAsh5114** [comment] 2025-01-01 10:44
Happy new year to you too! Thank you for the fixes :)
